# Generated by Django 3.2.15 on 2023-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_line_1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='account',
            name='address_line_2',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/default-user.png', upload_to='userprofile'),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='tokens',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='account',
            name='total_tokents_used',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
