# Generated by Django 3.2.15 on 2023-10-15 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='next_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='text_area_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='text_field_1',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
