# Generated by Django 3.2.15 on 2023-10-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20231015_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
