# Generated by Django 3.2.15 on 2023-10-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20231015_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='next_operation',
            new_name='prev_operation',
        ),
    ]
