# Generated by Django 3.2.15 on 2023-10-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_rename_next_operation_operation_prev_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='icon',
            field=models.ImageField(blank=True, upload_to='automation/icons'),
        ),
    ]
