# Generated by Django 3.2.15 on 2023-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_operation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='expected_output',
            field=models.IntegerField(blank=True, choices=[('List', 1), ('Text', 2), ('number', 3)], null=True),
        ),
    ]
