# Generated by Django 3.2.15 on 2023-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_operation_expected_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='expected_output',
            field=models.IntegerField(blank=True, choices=[('List', 1), ('Text', 2), ('List of Rows', 3), ('Single Row', 4)], null=True),
        ),
    ]
