# Generated by Django 3.2.15 on 2023-10-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_alter_operation_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='next_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_called_operation', to='automation.operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='expected_output',
            field=models.IntegerField(blank=True, choices=[(1, 'List of Text'), (2, 'Text'), (3, 'List of Rows'), (4, 'Single Row')], null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='prev_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_called_operation', to='automation.operation'),
        ),
    ]
