# Generated by Django 3.2.15 on 2023-10-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20231018_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='next_operation',
        ),
        migrations.AlterField(
            model_name='operation',
            name='prev_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_operations', to='automation.operation'),
        ),
    ]
