# Generated by Django 3.2.15 on 2023-10-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_auto_20231018_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationOutputKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('output_key', models.CharField(max_length=256)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.operation')),
            ],
        ),
    ]
