# Generated by Django 3.2.15 on 2023-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_operationoutputkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='automation/operations/files'),
        ),
    ]
