# Generated by Django 3.2.15 on 2023-10-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_operation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationoutputkeys',
            name='output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
