# Generated by Django 3.2.15 on 2023-10-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_operationoutputkeys_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operationoutputkeys',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_outputs', to='automation.operation'),
        ),
    ]
