# Generated by Django 3.2.15 on 2023-10-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_auto_20231021_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='text_field_2',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='operationoutputkeys',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
