# Generated by Django 3.2.15 on 2023-10-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_auto_20231022_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='iteration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
