# Generated by Django 4.0.10 on 2023-10-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_auto_20231022_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='total_operations',
            field=models.IntegerField(default=0),
        ),
    ]
