# Generated by Django 4.0.10 on 2023-10-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_operation_total_operations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='total_operations',
            new_name='total_iterations',
        ),
    ]
