# Generated by Django 4.0.10 on 2023-10-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_rename_total_operations_operation_total_iterations'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
