# Generated by Django 4.0.10 on 2023-10-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_automation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='image_url',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
