# Generated by Django 3.2.15 on 2023-03-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=512)),
                ('input_sequence', models.TextField()),
                ('description', models.TextField()),
                ('meta_description', models.CharField(max_length=256)),
                ('icon', models.ImageField(blank=True, upload_to='features/icons')),
            ],
        ),
        migrations.RemoveField(
            model_name='outputhistory',
            name='task',
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('recipe', models.TextField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='features.feature')),
            ],
        ),
        migrations.AddField(
            model_name='outputhistory',
            name='feature',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='features.feature'),
        ),
    ]
