# Generated by Django 3.2.15 on 2023-03-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20230304_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('input_key', models.CharField(max_length=256)),
                ('placeholder', models.CharField(max_length=256)),
                ('input_type', models.CharField(max_length=64)),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='input_sequence',
            new_name='prompt',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='features.feature'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('option_key', models.CharField(max_length=256)),
                ('input_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='features.inputsequence')),
            ],
        ),
    ]
