# Generated by Django 3.2.15 on 2023-03-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20230305_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='inputs',
            field=models.ManyToManyField(default=None, null=True, to='features.InputSequence'),
        ),
    ]
