# Generated by Django 3.2.15 on 2023-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_feature_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsequence',
            name='input_length',
            field=models.IntegerField(default=80),
        ),
    ]
