# Generated by Django 3.2.15 on 2023-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_inputsequence_input_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsequence',
            name='is_required',
            field=models.IntegerField(default=0),
        ),
    ]
