# Generated by Django 3.2.15 on 2023-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_inputsequence_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsequence',
            name='input_type',
            field=models.CharField(choices=[('text_field', 'Input Text Field'), ('textarea', 'TextArea'), ('select_picker', 'Select Picker')], max_length=64),
        ),
        migrations.AlterField(
            model_name='inputsequence',
            name='prompt',
            field=models.TextField(null=True),
        ),
    ]
