# Generated by Django 3.2.15 on 2023-03-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20230305_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsequence',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
