# Generated by Django 3.2.15 on 2023-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_favoritefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritefeature',
            name='is_fav',
            field=models.IntegerField(default=1),
        ),
    ]
