# Generated by Django 3.2.15 on 2023-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_favoritefeature_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritefeature',
            name='is_fav',
            field=models.IntegerField(default=0),
        ),
    ]
