# Generated by Django 3.2.15 on 2023-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_alter_favoritefeature_is_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=126)),
                ('code', models.CharField(default='', max_length=126)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='features.Category'),
        ),
    ]
