# Generated by Django 3.2.15 on 2023-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_auto_20230324_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputhistory',
            name='input_sequence',
            field=models.TextField(default=''),
        ),
    ]
