# Generated by Django 3.2.15 on 2023-03-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_outputhistory_input_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputhistory',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
