# Generated by Django 3.2.15 on 2023-10-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_outputhistory_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsequence',
            name='prompt',
            field=models.TextField(default='{user_input}'),
        ),
    ]
