# Generated by Django 3.2.15 on 2023-03-18 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('tokens', models.IntegerField(default=0)),
                ('is_expirable', models.IntegerField(default=0)),
                ('bg_image', models.ImageField(blank=True, upload_to='products/bg_image')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('is_expirable', models.IntegerField(default=0)),
                ('expiry', models.DateTimeField(default=None, null=True)),
                ('is_expired', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(default=0, max_length=256)),
                ('is_completed', models.IntegerField(default=0)),
                ('is_verified', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_gateway.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
