# Generated by Django 3.2.15 on 2023-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='replies',
        ),
        migrations.AddField(
            model_name='subscription',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
